version: '3.8'
services:
  python:
    build: .
    environment:
      - POSTGRES_HOST=postgis
      - POSTGRES_DB=gis
      - POSTGRES_PASSWORD=dessert
      - POSTGRES_USER=dheerajchand
    volumes:
      - /Users/dheerajchand/Documents/Professional/Siege_Analytics/docker_things/social_warehouse_pg_data:/opt/social_warehouse_pg_data
    restart: always
    networks:
      - social_warehouse_network
  postgis:
    image: postgis/postgis:13-master
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_PASSWORD=dessert
      - POSTGRES_USER=dheerajchand
      - POSTGRES_HOST_AUTH_METHOD=password
    ports:
      - 54324:5432
    volumes:
      - social_warehouse_pg_data:/var/lib/postgresql
    restart: always
    networks:
      - social_warehouse_network
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    ports:
      - 8082:8080
    restart: always
    environment:
      - ZEPPELIN_IN_DOCKER=true
    networks:
      - social_warehouse_network
    depends_on:
      - postgis

volumes:
  social_warehouse_pg_data:
networks:
  social_warehouse_network: null
