version: '3.8'
services:
  spark-master:
    image: da-spark-image
    entrypoint: ['spark_entrypoint.sh', 'master']
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./code:/opt/spark/code
      - ./data:/opt/spark/data
      - ./spark-master-defaults.properties:/opt/spark/conf/spark-defaults.conf
    ports:
      - '4040:4040'
      - '7077:7077'
      - '9090:8080'
      - '51810:51810'
      - '51811:51811'
      - '51812:51812'
      - '51813:51813'
      - '51814:51814'
    profiles:
      - all # disable this service atm
  #spark-history-server:
  #  image: da-spark-image
  #  depends_on:
  #    - spark-master
  #  volumes:
  #    - ./code/spark/spark-logs:/opt/spark/spark-events
  #    - ./spark-defaults.properties:/opt/spark/conf/spark-defaults.conf
  #  ports:
  #    - '18080:18080'
  spark-worker:
    image: da-spark-worker
    ports:
     - '9091:8081'
     - '51815:51815'
    entrypoint: ['spark_entrypoint.sh','worker']
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark/data
      - ./code:/opt/spark/code
      - ./code:/spark/spark-logs:/opt/spark/spark-events
      - ./spark-worker-defaults.properties:/opt/spark/conf/spark-defaults.conf
  python_computation:
    image: da-python-image 
    # build: .
    environment:
      - POSTGRES_HOST=postgis
      - POSTGRES_DB=gis
      - POSTGRES_PASSWORD=dessert
      - POSTGRES_USER=dheerajchand
    volumes:
      - .:/opt/social_warehouse/
    restart: always
    profiles:
      - all # disable this service atm
  postgis:
    image: postgis/postgis:13-master
    container_name: postgis
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_PASSWORD=dessert
      - POSTGRES_USER=dheerajchand
      - POSTGRES_HOST_AUTH_METHOD=password
    ports:
      - 54324:5432
    volumes:
      - social_warehouse_pg_data:/var/lib/postgresql
    restart: always
  zeppelin:
    image: apache/zeppelin:0.10.1
    ports:
      - 8082:8080
    restart: always
    environment:
      - ZEPPELIN_IN_DOCKER=true
    depends_on:
      - postgis
  maven:
    image: maven:3.6.3-jdk-11
    volumes:
      - ./.m2:/root/.m2
      - ./jars:/usr/src/app/jars
    working_dir: /usr/src/app
    command: sh -c "while true; do sleep 3600; done"

volumes:
  social_warehouse_pg_data:
  spark_logs: