version: '3.8'

services:

  python-computation:
    volumes:
      - .:/opt/social_warehouse/
    depends_on:
      - postgis

  postgis:
    restart: always

  zeppelin:
    depends_on:
      - postgis
    image: apache/zeppelin:0.10.1
    ports:
      - 8082:8080
    restart: always
    environment:
      - ZEPPELIN_IN_DOCKER=true

