version: '3.8'

services:

  py-comp:
    volumes:
      - .:/opt/social_warehouse/
    depends_on:
      - postgis

  postgis:
    restart: always

  zeppelin:
    image: ${CI_REGISTRY}/swh-zeppelin
    depends_on:
      - spark-gateway
    environment:
      - ZEPPELIN_IN_DOCKER=true
      - ZEPPELIN_SERVER_HOST=zeppelin
      - ZEPPELIN_NOTEBOOK_DIR='/notebooks'
      - SPARK_MASTER=spark://spark-gateway:7077
    ports:
      - 9027:8080
    volumes:
      - ./notebooks:/notebooks
      - ./sql:/sql
      - ./spark/logs:/opt/spark/spark-events

