version: '3.8'

services:

  postgis:
    image: postgis/postgis:13-master
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST_AUTH_METHOD
    ports:
      - 54324:5432
    volumes:
      - swh_pg_data:/var/lib/postgresql
    restart: always

volumes:
  swh_pg_data:
