
services:

  python-computation:
    image: swh-python-image
    build:
      args:
        - UBUNTU_BASE_IMAGE
        - PYTHON_VENV_PATH
      context: docker/python-computation
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER

